# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: kooyoseb.VulkanSupportCheckTool
PackageVersion: "1.0"
PackageLocale: ko-KR
Publisher: kooyoseb
PublisherUrl: https://kooyoseb.itch.io/
PublisherSupportUrl: https://kooyoseb.itch.io/
PrivacyUrl: https://kooyoseb.itch.io/
Author: kooyoseb
PackageName: VulkanSupportCheckTool
PackageUrl: https://kooyoseb.itch.io/vulkansupportchecktool
License: C:\Users\musek\Downloads\Vulkan_Support_Checker_License.rtf
LicenseUrl: http://mkawejbv.p-e.kr/
Copyright: kooyoseb
CopyrightUrl: http://mkawejbv.p-e.kr/
ShortDescription: Make sure your computer supports Vulkan
Description: Make sure your computer supports Vulkan
Moniker: Vulkan
Tags:
- VulkanSupportCheckTool
- kooyoseb
- Vulkan
Agreements:
- AgreementLabel: Vulkan Support Checker License Agreement
  AgreementUrl: http://mkawejbv.p-e.kr/
ReleaseNotes: Release_1.0
InstallationNotes: Installation is complete!!
Icons:
- IconUrl: https://img.itch.zone/aW1nLzIxMjg4ODAzLnBuZw==/original/2QMCYK.png
  IconFileType: png
ManifestType: defaultLocale
ManifestVersion: 1.9.0
