# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: kooyoseb.VulkanSupportCheckTool
PackageVersion: "1.0"
DefaultLocale: ko-KR
ManifestType: version
ManifestVersion: 1.9.0
